# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aux' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'youtube-ios-player-helper'

  # Pods for Aux

  target 'AuxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuxUITests' do
    # Pods for testing
  end

end
